### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by minorli96** [Pallab38/amass_SMPL#1]
Hi, when I study offical notebook code abount how to use AMASS datasets on SMPL, I am confuse about why SMPL pose parameter number is 24*3 = 72 , but in AMASS tutorial notebook, the number of parameter which control SMPL pose is 63. Your answer will help me a lot！

**Comment by Pallab38** [comment]
Hi, you are right about the number of SMPL pose parameter which is 63. If you include the hands then it becomes 72 as in SMPL+H (SMPL-H) model. I am referring to SMPL FAQ, page:7 [SMPL-made-simple-FAQs.pdf](https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf) and from the author Nima Ghorbani
``
 just a quick note: as described within the AMASS text, wherever we mention SMPL in the paper, we actually mean SMPL+H
``
Please look at [ Amass Github: Issue 3](https://github.com/nghorbani/amass/issues/3#issuecomment-565714925) for more details. I hope it helps :).

**Comment by minorli96** [comment]
@Pallab38 
Thank you very much ，this is very helpful for me！ wish you all the best
